version: '3.8'

services:
  stream_processor:
    build:
      context: ../..
      dockerfile: scripts/docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../../config:/app/config
    environment:
      - LOG_LEVEL=INFO
    networks:
      - stream_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  monitoring:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ../../config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - stream_network

networks:
  stream_network:
    driver: bridge
